web_server_rg             = "web-rg"
resource_prefix           = "web-server"
# web_server_address_prefix = "1.0.1.0/24"
web_server_name           = "web"
environment               = "production"
#environment               = "dev"
web_server_count          = 2
terraform_script_version  = "1.0.0"
domain_name_label         = "balivo-learn-tf-web"